### ISSUE TITLE
vsdeinterlace issue list

### ISSUE THREAD

**Issue by ghost** [Jaded-Encoding-Thaumaturgy/vs-deinterlace#16]
- [x] check_ivtc_pattern implementation is very inaccurate, doing it properly (i.e. how yatta does it) would be slower than manual checking, may be better to remove
- [x] all tivtc functions should be stubbed until the plugin is fixed to prevent ruining encodes
- [x] check_patterns and seek_cycle are not useful and should be removed
- [x] PARser is more fit to vstools instead of vsdeinterlace
- [x] Make sivtc/jivtc function with an arbitrary cycle length
- [ ] #31
- [ ] #32
- [x] fix_telecined_fades is missing match to brighter & match to darker field

**Comment by Setsugennoao** [comment]
> check_ivtc_pattern ... may be better to remove
> check_patterns and seek_cycle are not useful and should be removed
@LightArrowsEXE what do you think about this? You made those functions.

**Comment by LightArrowsEXE** [comment]
> > check_ivtc_pattern ... may be better to remove
> > check_patterns and seek_cycle are not useful and should be removed
> 
> @LightArrowsEXE what do you think about this? You made those functions.

`check_ivtc_pattern` and `check_patterns` form a pair. The idea is that you can quickly run `check_patterns` over a clip to determine whether it's a clean IVTC with a single pattern. I wouldn't call it useless personally, as there are cases where this can very quickly get you the correct pattern (see for example the Tales OPs I sent to sinc a while back).

`seek_cycle` was something I wrote for fun, and I could see the argument for it being useless in a VS environment. It would have its uses in something like a Python port of wobbly and for strictly showcasing how telecining looks. It can also easily show full interlacing, but that's also something the user can simply do by stepping through frames themselves.

I'd say keep `check_patterns` (maybe incorporating `check_ivtc_pattern` in there as a private function), and consider removing `seek_cycle`, or moving it back to `lvsfunc` under `comparison.py` or something. In the event we do rewrite wobbly, rewriting that piece of code should be fairly trivial.

**Comment by wiwaz** [comment]
Note that the `pulldown_credits` and `qtgmc` tasks are blocked by [vs-denoise/issues/69](https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/issues/69)
